new function(){

	this.hello = function(params){
		return rb.create().newInner().property('name','ryun').build().toJsonObject();
	}, 
	
	this.greeting = function(params){
		return rb.create().newInner().property('name', params.asString('name'))
			.property('location', params.asString('location'))
			.property('money', params.asInt('money'))
			.inner('friends').property('name', params.asStrings('friends')).build().toJsonObject();
	}, 
	
	this.refTos = function(params){
		session.tranSync(function(wsession){
			wsession.pathBy("/bleujin").property("name", "bleujin").refTos("self", ["/bleujin"]) ;
		}) ;
	}, 
	
	this.langError = function(params){
		session.tranSync(function(wsession){
			wsession.pathBy("/bleujin").property("name", "bleujin").refTos("self", ["/bleujin"]) ;
//			wsession.pathBy("/bleujin").property("name", "bleujin").refTos("self", ["/bleujin")]) ;
		}) ;
	}, 
	
	this.onexception = function(params){
		return rb.notsuchMethod() ;
	}


} ;